# MODULES (EXTERNAL)
# ---------------------------------------------------------------------------------------------------------------------
from pathlib import Path
from typing import List, TYPE_CHECKING
# ---------------------------------------------------------------------------------------------------------------------

# MODULES (INTERNAL)
# ---------------------------------------------------------------------------------------------------------------------
from src.utils.strings import DocStrings

if TYPE_CHECKING:
    from src.models.structures import ModuleInfo
# ---------------------------------------------------------------------------------------------------------------------

# OPERATIONS / CLASS CREATION / GENERAL FUNCTIONS
# ---------------------------------------------------------------------------------------------------------------------

__all__ = ['ReadmeGenerator']

README_FILE = 'README.md'

class ReadmeGenerator:
    """
    Utility for building and persisting project documentation in README format.

    This class concentrates **presentation** (Markdown formatting) and **output** (writing to disk) operations 
    based on the structured results produced by the code analyzer (`ModuleInfo`). It does not perform static analysis: 
    it only transforms already processed data into a readable document.
    """

    @staticmethod
    def render(modules: List['ModuleInfo'], directory: str, *, cleaned: List[str] = ['*', '`']) -> str:
        """
        Generates the contents of the README file from the information analyzed from the project modules.

        It scans the results obtained by the code analyzer (`ModuleInfo`) and builds a document in Markdown format
        that includes the repository description, the list of modules, their classes, methods, and functions, along 
        with the associated docstrings when available.

        Args:
            modules (List[ModuleInfo]):
                List of `ModuleInfo` objects representing the analyzed modules in the repository.
            directory (str):
                Base path of the analyzed repository. It is displayed in the header of the generated README.
            cleaned (List[str]):
                List of tokens to be removed from the readme.

        Returns:
            str:
                Text string with the complete content of the README formatted in Markdown.
        """
        lines = []
        
        lines.append('# 📘 Documentation generated by AutoDocMind\n')
        lines.append(f'## *Repository analyzed*: `{Path(directory).resolve().name}`\n')

        for module in sorted(modules, key=lambda module: module.path):
            relative = Path(module.path).resolve().relative_to(Path(directory).resolve())
            lines.append(f'## 🧩 Module: `{relative.as_posix()}`\n')

            if not module.classes and not module.functions:
                lines.append('*This module does not contain documentation on classes or functions.*')
            else:
                if module.classes:
                    for clss in module.classes:
                        lines.append(f'### Class: `{clss.name}`\n')

                        if clss.doc:
                            lines.append(DocStrings.to_readme(clss.doc, cleaned=cleaned) + '\n')

                        for meth in clss.methods:
                            lines.append(f'#### Method: `{meth.name}` (*Declared in line: {meth.lineno}*)\n')

                            if meth.doc:
                                lines.append(DocStrings.to_readme(meth.doc, cleaned=cleaned) + '\n')

                if module.functions:
                    lines.append('### Functions\n')

                    for func in module.functions:
                        lines.append(f'#### `{func.name}` - *Declared in line: {func.lineno}*\n')

                        if func.doc:
                            lines.append(DocStrings.to_readme(func.doc, cleaned=cleaned) + '\n')

        return '\n'.join(lines)

    @staticmethod
    def write(text: str, output: str) -> Path:
        """
        Write the generated README content to the file system.

        Create the output directory if it does not exist and save the received text to a Markdown.

        Args:
            text (str):
                README content in Markdown format, usually generated by `render_readme`.
            output (str):
                Path of the directory where the file will be stored. If it does not exist, 
                it is created automatically.

        Returns:
            Path:
                Full path of the generated README file.
        """
        out = Path(output)
        out.mkdir(parents=True, exist_ok=True)

        target = out / README_FILE

        target.write_text(text, encoding='utf-8')

        return target
    
# ---------------------------------------------------------------------------------------------------------------------
# END OF FILE