# MODULES (EXTERNAL)
# ---------------------------------------------------------------------------------------------------------------------
from __future__ import annotations

from pathlib import Path
from typing import List, Optional, TYPE_CHECKING
# ---------------------------------------------------------------------------------------------------------------------

# MODULES (INTERNAL)
# ---------------------------------------------------------------------------------------------------------------------
from src.tools.docstring import format_docstring
from common.constants import ALGORITHM_VERSION, NO_METHOD, NO_FUNCTION, NO_CLASS, NO_MODULE, NO_ATTRIBUTE

if TYPE_CHECKING:
    from src.models import ModuleInfo
# ---------------------------------------------------------------------------------------------------------------------

# OPERATIONS / CLASS CREATION / GENERAL FUNCTIONS
# ---------------------------------------------------------------------------------------------------------------------

def generate_content(modules: List[ModuleInfo], repository: str, *, cleaned: Optional[List[str]] = None) -> str:
    """
    Generates the contents of the README file from the information analyzed from the project modules.

    It scans the results obtained by the code analyzer (`ModuleInfo`) and builds a document in Markdown format
    that includes the repository description, the list of modules, their classes, methods, and functions, along 
    with the associated docstrings when available.

    Args:
        modules (List[ModuleInfo]):
            List of `ModuleInfo` objects representing the analyzed modules in the repository.
        repository (str):
            Base path of the repository or project to be analyzed.
        cleaned (List[str], optional):
            List of tokens to be removed from the readme.

    Returns:
        str:
            Text string with the complete content of the README formatted in Markdown.
    """
    if cleaned is None:
        cleaned = ['`']

    lines: List[str] = []
    lines.append(f'# 📑 Documentation generated by Codemnesis - v.{ALGORITHM_VERSION}\n')
    lines.append(f'## 🗃️ *Repository analyzed*: `{Path(repository).resolve().name}`\n')

    for module in sorted(modules, key=lambda module: module.path):
        relative = Path(module.path).resolve().relative_to(Path(repository).resolve())
        lines.append(f'## 🗂️ Module: `{relative.as_posix()}`\n')

        if not module.classes and not module.functions:
            lines.append(f'*{NO_MODULE}*\n')
        else:
            if module.classes:
                for cls in module.classes:
                    if cls.doc:
                        lines.append(
                            f'### 📜 Class: `{cls.name}`\n'
                            f'{format_docstring(cls.doc, cleaned)}\n'
                        )
                    else:
                        lines.append(f'### 📜 Class: `{cls.name}` - *{NO_CLASS}*\n')

                    if cls.decorators:
                        decorators = '\n- '.join(cls.decorators)
                        lines.append(f'*Decorators:*\n- {decorators}\n')

                    for attr in cls.attributes:
                        if attr.doc:
                            lines.append(
                                f'#### 📌 *Attribute declared in line {attr.lineno}*: `{attr.name}`\n'
                                f'{format_docstring(attr.doc, cleaned)}\n'
                            )
                        else:
                            lines.append(
                                f'#### 📌 *Attribute declared in line {attr.lineno}*: `{attr.name}` - '
                                f'*{NO_ATTRIBUTE}*\n'
                            )

                    for meth in cls.methods:
                        if meth.doc:
                            lines.append(
                                f'#### 🛠️ *Method declared in line {meth.lineno}*: `{meth.name}`\n'
                                f'{format_docstring(meth.doc, cleaned)}\n'
                            )
                        else:
                            lines.append(
                                f'#### 🛠️ *Method declared in line {meth.lineno}*: `{meth.name}` - '
                                f'*{NO_METHOD}*\n'
                            )
                        
                        if meth.decorators:
                            decorators = '\n- '.join(meth.decorators)
                            lines.append(f'*Decorators:*\n- {decorators}\n')

            if module.functions:
                lines.append('### 📃 Functions\n')
                for func in module.functions:
                    if func.doc:
                        lines.append(
                            f'#### 🛠️ *Function declared in line {func.lineno}*: `{func.name}`\n'
                            f'{format_docstring(func.doc, cleaned)}\n'
                        )
                    else:
                        lines.append(
                            f'#### 🛠️ *Function declared in line {func.lineno}*: `{func.name}` - '
                            f'*{NO_FUNCTION}*\n'
                        )

    return '\n'.join(lines)

# ---------------------------------------------------------------------------------------------------------------------
# END OF FILE